### ISSUE TITLE
Error message when running "Python app. py"

### ISSUE THREAD

**Issue by mario0718** [pengHTYX/Era3D#11]
Terminal running with errors: "Input tensor shape: torch. Size ([12, 3, 512, 512]). Additional information: {}.",I found that it is related to line 186 of the app. py file "imgs_in=realrange (imgs_in," B Nv C H W ->(B Nv) C H W ")"，Can you help me solve this? Thank you!
![1](https://github.com/pengHTYX/Era3D/assets/46362714/f2f44015-c2e3-4f08-8741-659bc7fa2646)

**Comment by pengHTYX** [comment]
Hi, I have fixed this bug, can you try again?

**Comment by mario0718** [comment]
> 你好，我已经修复了这个错误，你能再试一次吗？

ok! Excuse me. After i replaced the file, the terminal encountered the following error again:
![2](https://github.com/pengHTYX/Era3D/assets/46362714/b6b33256-ba8b-4622-b176-0c885a06f8b6)
It seems that the variable 'imgs_in' is not declared!

**Comment by pengHTYX** [comment]
sry, try again now?

**Comment by mario0718** [comment]
> sry, try again now?

The following error has occurred:
![3](https://github.com/pengHTYX/Era3D/assets/46362714/7faeca16-8374-4c6e-bd1f-08943c31d1ab)

**Comment by pengHTYX** [comment]
Could you please clone the source code from [huggingface demo](https://huggingface.co/spaces/pengHTYX/Era3D_MV_demo/tree/main). The code should work correctly.

**Comment by mario0718** [comment]
> Could you please clone the source code from [huggingface demo](https://huggingface.co/spaces/pengHTYX/Era3D_MV_demo/tree/main). The code should work correctly.

ok! thank you
