### ISSUE TITLE
Questions about embeds under mvdiffusion/data/fixed_prompt_embeds_6view?

### ISSUE THREAD

**Issue by abc2cba** [pengHTYX/Era3D#13]
Is the embeds under mvdiffusion/data/fixed_prompt_embeds_6view sort of trained Textual Inversion or simply encoded prompt embedding?

**Comment by pengHTYX** [comment]
We use the encoded prompt embedding directly.

**Comment by abc2cba** [comment]
> We use the encoded prompt embedding directly.

Could you provide the detail prompts?

**Comment by pengHTYX** [comment]
Please see in [this function](https://github.com/pengHTYX/Era3D/blob/bdcaced9282af29c0c19872c753d029c2c033bc4/mvdiffusion/data/generate_fixed_text_embeds.py#L15).

**Comment by Misakatyan** [comment]
> Please see in [this function](https://github.com/pengHTYX/Era3D/blob/bdcaced9282af29c0c19872c753d029c2c033bc4/mvdiffusion/data/generate_fixed_text_embeds.py#L15).
I have a question about this. I tried running the code, but there were significant differences between the resulting pt file and the given file. For example, out of 78848 values in the embedding result of "front", only 8352 were consistent
