### ISSUE TITLE
Spatial misalignment after rendering the mesh

### ISSUE THREAD

**Issue by mario0718** [pengHTYX/Era3D#18]
Hi,The handlebar space of electric vehicles is misaligned，How to optimize and solve this problem？
![1](https://github.com/pengHTYX/Era3D/assets/46362714/0bebae52-3164-40bc-9b3d-98b3b0bf1b97)
![2](https://github.com/pengHTYX/Era3D/assets/46362714/8c39b95e-991b-4993-b54c-f85bad8bff37)
![3](https://github.com/pengHTYX/Era3D/assets/46362714/9c04cbbf-eac2-471f-bdb1-be2ee826f698)
![4](https://github.com/pengHTYX/Era3D/assets/46362714/c5fdfd23-d2fa-4e21-a628-2550ff34f4c3)

**Comment by mario0718** [comment]
At present, after continuously modifying the configuration item parameters, it has been normal, as summarized below:

1. Some potential improvements: more iterations; 

- larger model.geometry.xyz_encoding_config.update_steps; 
- larger model.geometry.xyz_encoding_config.n_features_per_level; 
- larger model.geometry.xyz_encoding_config.log2_hashmap_size; adopting curvature loss.
`cat instant-nsr-pl/configs/neuralangelo-ortho-wmask.yaml`
    `xyz_encoding_config: `
      `otype: ProgressiveBandHashGrid`
     ` n_levels: 10 # 12 modify`
      `n_features_per_level: 8`
      `log2_hashmap_size: 19`
      `base_resolution: 16`
      `per_level_scale: 1.3195079107728942`
      `include_xyz: true`
      `start_level: 4`
      `start_step: 0`
      `update_steps: 2000`
2. Complex cases require long training
In the given config files, the number of training steps is set to 20000 by default. This works well for objects of simple geometries, like the chair scene in the NeRF-Synthetic dataset. However, for more complicated cases where many thin structures occur, more training iterations are needed to get high quality results. This could simply be done by setting trainer.max_steps to a higher value, like 50000 or 100000.

`cat instant-nsr-pl/configs/neuralangelo-ortho-wmask.yaml`

`trainer:`
  `max_steps: 20000`
  `log_every_n_steps: 100`
  `num_sanity_val_steps: 0`
  `val_check_interval: 5000`
  `limit_train_batches: 1.0`
  `limit_val_batches: 12`
  `enable_progress_bar: true`
  `precision: 32`

3. result-outputs
![it20000-0](https://github.com/pengHTYX/Era3D/assets/46362714/f451cfdd-b441-4e49-a9b3-ba4f161f3e46)
![it20000-1](https://github.com/pengHTYX/Era3D/assets/46362714/2a8ebdc3-2c0d-4627-b527-45a892e0fa81)
![it20000-2](https://github.com/pengHTYX/Era3D/assets/46362714/232ab45f-6133-47a5-ba25-0f722c2d9e60)
![it20000-3](https://github.com/pengHTYX/Era3D/assets/46362714/c9814d64-b97f-4993-9b34-3a1c8952ba41)
![it20000-4](https://github.com/pengHTYX/Era3D/assets/46362714/b4f09909-2021-4959-bdb0-3a255b71476d)
![it20000-5](https://github.com/pengHTYX/Era3D/assets/46362714/aa4ce032-f686-4788-9c0b-212835882f76)
![20240620134620](https://github.com/pengHTYX/Era3D/assets/46362714/19a64c34-f090-437f-82d4-195d9df0afbb)

**Comment by realisticdreamer114514** [comment]
Sorry @mario0718 for commenting on this 2 months after you closed this issue, but I wish to see your metrics.csv of that motorbike object, for various loss metrics at the `max_steps` you used, so I can gauge how refined my meshes are. 
It should be located in `Era3D\instant-nsr-pl\exp\[name]\@[date]-[time]\csv_logs`

![image](https://github.com/user-attachments/assets/233e8d1f-fb7f-44e2-9bd6-f6f59bdfad9d)
![image](https://github.com/user-attachments/assets/e7af36b8-fa41-460a-b18a-0faa4e67bfec)

(I stopped instant-nsr-pl after 15000 steps which should be undertrained by your standard)
Thank you.
