### ISSUE TITLE
"TypeError: unsupported operand type(s) for /: 'str' and 'int'" when executing code at .\mvdiffusion\data\single_image_dataset.py, line 182

### ISSUE THREAD

**Issue by realisticdreamer114514** [pengHTYX/Era3D#19]
> python test_mvdiffusion_unclip.py --config configs/test_unclip-512-6view.yaml pretrained_model_name_or_path='pengHTYX/MacLab-Era3D-512-6view' validation_dataset.crop_size='420' validation_dataset.root_dir=input seed=810 save_dir='mv_res' save_mode='rgb'
{'pretrained_model_name_or_path': 'pengHTYX/MacLab-Era3D-512-6view', 'revision': None, 'num_views': 6, 'validation_dataset': {'prompt_embeds_path': 'mvdiffusion/data/fixed_prompt_embeds_6view', 'root_dir': 'input', 'num_views': 6, 'bg_color': 'white', 'img_wh': [512, 512], 'num_validation_samples': 1000, 'crop_size': '420'}, 'pred_type': 'joint', 'save_dir': 'mv_res', 'save_mode': 'rgb', 'seed': 810, 'validation_batch_size': 1, 'dataloader_num_workers': 1, 'local_rank': -1, 'pipe_kwargs': {'num_views': 6}, 'validation_guidance_scales': [3.0], 'pipe_validation_kwargs': {'num_inference_steps': 40, 'eta': 1.0}, 'validation_grid_nrow': 6, 'regress_elevation': True, 'regress_focal_length': True, 'unet_from_pretrained_kwargs': {'unclip': True, 'sdxl': False, 'num_views': 6, 'sample_size': 64, 'zero_init_conv_in': False, 'regress_elevation': True, 'regress_focal_length': True, 'camera_embedding_type': 'e_de_da_sincos', 'projection_camera_embeddings_input_dim': 4, 'zero_init_camera_projection': False, 'num_regress_blocks': 3, 'cd_attention_last': False, 'cd_attention_mid': False, 'multiview_attention': True, 'sparse_mv_attention': True, 'selfattn_block': 'self_rowwise', 'mvcd_attention': True, 'use_dino': False}, 'enable_xformers_memory_efficient_attention': True}
The config attributes {'decay': 0.9999, 'inv_gamma': 1.0, 'min_decay': 0.0, 'optimization_step': 40000, 'power': 0.6666666666666666, 'update_after_step': 0, 'use_ema_warmup': False} were passed to UNetMV2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 9/9 [00:01<00:00,  7.35it/s]
input\test0.png
Traceback (most recent call last):
  File "D:\Era3D\test_mvdiffusion_unclip.py", line 233, in <module>
    main(cfg)
  File "D:\Era3D\test_mvdiffusion_unclip.py", line 199, in main
    validation_dataset = SingleImageDataset(
                         ^^^^^^^^^^^^^^^^^^^
  File "D:\Era3D\mvdiffusion\data\single_image_dataset.py", line 131, in __init__
    image, alpha = self.load_image(os.path.join(self.root_dir, file), bg_color, return_type='pt')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Era3D\mvdiffusion\data\single_image_dataset.py", line 182, in load_image
    scale = self.crop_size / max(h, w)
            ~~~~~~~~~~~~~~~^~~~~~~~~~~
TypeError: unsupported operand type(s) for /: 'str' and 'int'

(I created a "input" folder for my own images)

**Comment by chilyanin** [comment]
The same issue ((

**Comment by pengHTYX** [comment]
hi, you should check the type of 'elf.crop_size'.  But most of the users did not meet this error.

**Comment by chilyanin** [comment]
Thank you. so there is an error in example https://github.com/pengHTYX/Era3D?tab=readme-ov-file#inference

**Comment by pengHTYX** [comment]
Can you please provide the image you used? I'd be happy to try to fix the bug. Alternatively, you can also take a try on our [huggingface demo](https://huggingface.co/spaces/pengHTYX/Era3D_MV_demo).

**Comment by chilyanin** [comment]
I'm using this command `python test_mvdiffusion_unclip.py --config configs/test_unclip-512-6view.yaml pretrained_model_name_or_path='MacLab-Era3D-512-6view' validation_dataset.crop_size=420 validation_dataset.root_dir=examples seed=600 save_dir='mv_res' save_mode='rgb'`

**Comment by chilyanin** [comment]
I want to get a textured mesh so can't use demo ((

**Comment by realisticdreamer114514** [comment]
> hi, you should check the type of 'elf.crop_size'. But most of the users did not meet this error.

This is right, I should have realized it is not a code issue but rather "validation_dataset.crop_size" in the inference command accepts integers (420) instead of a string ('420').
