### ISSUE TITLE
License ? 

### ISSUE THREAD

**Issue by rakataprime** [pengHTYX/Era3D#2]
This is fantastic work!! Congrats! I noticed the repo was missing a license and was wondering if you were intending to open source this at some point ?

**Comment by pengHTYX** [comment]
> This is fantastic work!! Congrats! I noticed the repo was missing a license and was wondering if you were intending to open source this at some point ?

hi， thank you for your interest in our project. I have added the [licence](https://github.com/pengHTYX/Era3D/blob/main/LICENCE).

**Comment by rakataprime** [comment]
Awesome!!! Thanks

**Comment by tak-s** [comment]
MIT(License file)? or AGPL-3.0(in README)?

**Comment by pengHTYX** [comment]
> MIT(License file)? or AGPL-3.0(in README)?

hi, our project is under AGPL-3.0 as in README. I have updated it.
