### ISSUE TITLE
Please be more informative about that only HF repo works

### ISSUE THREAD

**Issue by kungfooman** [pengHTYX/Era3D#21]
Everyone thinks that this repo is the "source of truth", but `python app.py` will just generate an error once you try to generate normals.

Then the solution is: Use https://huggingface.co/spaces/pengHTYX/Era3D_MV_demo instead

But why have a broken repository and a working one?

**Comment by pengHTYX** [comment]
Hi, so sorry for the previous inconsistency. I have addressed the issue and provided the step-by-step instructions for the local demo in [readme](https://github.com/pengHTYX/Era3D/blob/main/README.md).

**Comment by kungfooman** [comment]
Oh nice: https://github.com/pengHTYX/Era3D/commit/d6edf10b4b400a512a2c5be02960825e33b9b19d

I'm currently not on my test machine, but I'm sure the old type mismatch error is fixed now with these changes :+1: 

Thank you @pengHTYX for your quick work, highly appreciated! :1st_place_medal:
