### ISSUE TITLE
I wonder if we can generate 3D models

### ISSUE THREAD

**Issue by wangzhiisvery666** [pengHTYX/Era3D#31]
I wonder if we can generate 3D models

**Comment by pengHTYX** [comment]
Please refer to [Inference](https://github.com/pengHTYX/Era3D/blob/d6edf10b4b400a512a2c5be02960825e33b9b19d/README.md?plain=1#L42) for reconstructing 3D mesh.

**Comment by wangzhiisvery666** [comment]
谢谢你，我解决了
