### ISSUE TITLE
position embeddings inconsistency

### ISSUE THREAD

**Issue by Misakatyan** [pengHTYX/Era3D#37]
I have a question about this. I tried running the code in mvdiffusion/data/generate_fixed_text_embeds.py, but there were significant differences between the resulting pt file and the given file. For example, out of 78848 values in the embedding result of "front", only 8352 were consistent

**Comment by pengHTYX** [comment]
I'm afraid that you should run the function `generate_mv_embeds` rather than directly run the `generate_fixed_text_embeds.py`. I hope this helps.
