### ISSUE TITLE
Commercial use?

### ISSUE THREAD

**Issue by BillCls33** [pengHTYX/Era3D#40]
Hi, I'm trying this tool for my company. Instead of shooting you a business email, I'm asking on my own (and for my boss too): is it fine for us to commercially use the end product (3D meshes generated using image designs we created & own) as end-users of this unaltered repo? Do we need to credit your team or do anything for you to use this?

**Comment by pengHTYX** [comment]
Hi, sorry for the late reply. Unfortunately, this project is temporarily only for research purposes and not for commercial use. If you have any further questions, please get in touch with me via lpstarry@163.com.

**Comment by BillCls33** [comment]
OK, we are also using it for evaluation so far.
