### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by xiyichen** [pengHTYX/Era3D#5]
Thanks for your amazing work! Do have a plan to release the training code for finetuning the SD 2.1 on the objaverse dataset?

**Comment by pengHTYX** [comment]
> Thanks for your amazing work! Do have a plan to release the training code for finetuning the SD 2.1 on the objaverse dataset?

Hi, thanks for your attention.  we will release the full training codes and filtered object list in the coming months.  If you have any other questions or suggestions, please feel free to reach out to us.
