### ISSUE TITLE
About training data.

### ISSUE THREAD

**Issue by Jackiemin233** [pengHTYX/Era3D#51]
Thanks for your great work!
I want to fine-tune this model with my own dataset. Could you please provide some details or tutorials about data preprocessing and organization?
Appreciate your time again!

**Comment by pengHTYX** [comment]
Hi, thanks for your interest. Please refer to this [issue](https://github.com/pengHTYX/Era3D/issues/9#issuecomment-2144491059).

**Comment by Jackiemin233** [comment]
Thanks for your quick reply. My training is on. Thanks!
