### ISSUE TITLE
training set object list

### ISSUE THREAD

**Issue by za-cheng** [pengHTYX/Era3D#9]
Thanks for open source and I enjoyed reading your paper. A few questions about training set

- Could you share your training set object list? (I found several jsons in this repo but am unsure which one the model was trained on)
- Can you comment on what criteria you used to select this subset?

**Comment by pengHTYX** [comment]
hi, thanks for your attention. Actually, we have not released the training config and training object lists.  We filter Objaverse by several criteria:                             
- In some cases, the faces are flipped, which affects the normal rendering. We filter them by comparing the normal direction between renderings and calculated by depth;
- BLENDER_EEVEE may fail to render normal maps of objs with transparent material, so we calculate the IOU of color images and normal maps and filter them by a threshold.
- We train Era3D with the views at the elevation of 0 degrees.   So we exclude the objects whose 0-elevation view is over-thin to prevent our model from generating over-flatten novel views. 
- Finally, we roughly remove the cases with wired poses, helping our model to predict approximate elevation. 
By the way, we will release all of them in the coming weeks.

**Comment by za-cheng** [comment]
Thanks so much for the quick reply. Could you elaborate on the third point - what was the procedure to identify thin objects? And did you select from the entire objectverse or just LVIS?

**Comment by pengHTYX** [comment]
> Thanks so much for the quick reply. Could you elaborate on the third point - what was the procedure to identify thin objects? And did you select from the entire objectverse or just LVIS?

For example, calculate the ratio of the width (W) and height (H) of the foreground mask in the front view and side view.
